---
title: "Analysis of Covid-19 on Climate Change"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(measurements)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggmap)
library(stringr)
library(choroplethr)
library(choroplethrMaps)
library(lubridate)

waterloo_2019 <- read.csv('./datasets/Waterloo_Municipal_Iowa2019.csv')
waterloo_2020 <- read.csv('./datasets/Waterloo_Municipal_Iowa2020.csv')
waterloo_2021 <- read.csv('./datasets/Waterloo_Municipal_Iowa2021.csv')
nyc_2019 <- read.csv('./datasets/JFK_International_NewYork2019.csv')
nyc_2020 <- read.csv('./datasets/JFK_International_NewYork2020.csv')
nyc_2021 <- read.csv('./datasets/JFK_International_NewYork2021.csv')

months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
```

# Aggregate NYC Dataset
```{r}
nyc_2019_clean       <- nyc_2019[-c(1, 3:11, 14:27, 29:36, 39:69, 72:74, 76:125)]
nyc_2019_clean$DATE  <- as.Date(nyc_2019_clean$DATE)
nyc_2019_clean$Year  <- year(ymd(nyc_2019_clean$DATE))
nyc_2019_clean$Month <- month(ymd(nyc_2019_clean$DATE))
nyc_2019_clean$Day   <- day(ymd(nyc_2019_clean$DATE))

nyc_2019_clean <- nyc_2019_clean %>% relocate(HourlyPresentWeatherType, .after = Day) %>%
                        relocate(HourlyPrecipitation, .after = HourlyPresentWeatherType) %>%
                        relocate(Year, .after = DATE) %>% 
                        relocate(Month, .after = Year) %>% 
                        relocate(Day, .after = Month) %>%                                                              filter(!is.na(DailyAverageDryBulbTemperature) | !is.na(MonthlyMeanTemperature))

nyc_2020_clean       <- nyc_2020[-c(1, 3:11, 14:27, 29:36, 39:69, 72:74, 76:125)]
nyc_2020_clean$DATE  <- as.Date(nyc_2020_clean$DATE)
nyc_2020_clean$Year  <- year(ymd(nyc_2020_clean$DATE))
nyc_2020_clean$Month <- month(ymd(nyc_2020_clean$DATE))
nyc_2020_clean$Day   <- day(ymd(nyc_2020_clean$DATE))

nyc_2020_clean <- nyc_2020_clean %>% relocate(HourlyPresentWeatherType, .after = Day) %>%
                        relocate(HourlyPrecipitation, .after = HourlyPresentWeatherType) %>%
                        relocate(Year, .after = DATE) %>% 
                        relocate(Month, .after = Year) %>% 
                        relocate(Day, .after = Month) %>%                                                              filter(!is.na(DailyAverageDryBulbTemperature) | !is.na(MonthlyMeanTemperature))

nyc_2021_clean       <- nyc_2021[-c(1, 3:11, 14:27, 29:36, 39:69, 72:74, 76:125)]
nyc_2021_clean$DATE  <- as.Date(nyc_2021_clean$DATE)
nyc_2021_clean$Year  <- year(ymd(nyc_2021_clean$DATE))
nyc_2021_clean$Month <- month(ymd(nyc_2021_clean$DATE))
nyc_2021_clean$Day   <- day(ymd(nyc_2021_clean$DATE))

nyc_2021_clean <- nyc_2021_clean %>% relocate(HourlyPresentWeatherType, .after = Day) %>%
                        relocate(HourlyPrecipitation, .after = HourlyPresentWeatherType) %>%
                        relocate(Year, .after = DATE) %>% 
                        relocate(Month, .after = Year) %>% 
                        relocate(Day, .after = Month) %>%                                                              filter(!is.na(DailyAverageDryBulbTemperature) | !is.na(MonthlyMeanTemperature))

nyc_clean <- rbind(nyc_2019_clean, nyc_2020_clean, nyc_2021_clean) # combine nyc data sets


nyc_clean$`Month Formatted` <- factor(nyc_clean$Month, levels = c(1,2,3,4,5,6,7,8,9,10,11,12), 
                     labels = months)

nyc_clean <- nyc_clean %>% relocate(`Month Formatted`, .after = Month)

rm(nyc_2019)
rm(nyc_2020)
rm(nyc_2021)
rm(nyc_2019_clean)
rm(nyc_2020_clean)
rm(nyc_2021_clean)
```

# Aggregate Waterloo Dataset
```{r}

```