---
title: "Climate Change Analysis in USA Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***

**Team members:** GaJin Kim, Jayant Shah

**Aggregated Links to Data Sets:** 


JFK INTERNATIONAL AIRPORT, NY US: 
https://www.ncei.noaa.gov/access/search/data-search/local-climatological-data?bbox=40.965,-74.257,40.465,-73.757&startDate=2019-01-01T00:00:00&endDate=2022-01-01T23:59:59&dataTypes=DailyAverageDryBulbTemperature&dataTypes=DailyPrecipitation&dataTypes=HourlyPresentWeatherType&dataTypes=MonthlyMaximumTemperature&dataTypes=MonthlyMeanTemperature&dataTypes=MonthlyMinimumTemperature&pageNum=1&stations=74486094789

WATERLOO MUNICIPAL AIRPORT, IA US: 
https://www.ncei.noaa.gov/access/search/data-search/local-climatological-data?bbox=43.501,-96.641,40.372,-90.143&startDate=2019-01-01T00:00:00&endDate=2022-01-01T23:59:59&dataTypes=DailyAverageDryBulbTemperature&dataTypes=DailyPrecipitation&dataTypes=HourlyPresentWeatherType&dataTypes=MonthlyMaximumTemperature&dataTypes=MonthlyMeanTemperature&dataTypes=MonthlyMinimumTemperature&pageNum=1&place=State%20or%20Province:14&stations=72548094910

**Overview:** Comparing how the corona virus has affected average temperatures in different counties across the United States (years 2019 - 2021). The ones we will be analyzing in depth will be a suburban city: Waterloo, IA and a density populated urban city, New York City, NY. The data set contains over 100 different columns, however, we only plan to analyze 6 of them: 'DailyAverageDryBulbTemperature', 'DailyPrecipitation', 'HourlyPresentWeatherType', 'MonhtlyMaximumTemperature', 'MonhtlyMeanTemperature', and 'MonthlyMinimumTemperature'. Each of the combined datasets will include over a thousand rows (365 days over 3 years).

**Plan for exploratory analysis:** We plan to answer the following questions through our exploratory analysis of the dataset:

i.How has the mean temperature changed when covid started, during covid and after covid for the counties which we have chose?

ii.How has the demographic of a densely populated city affected the temperature during covid?

iii.How has the demographic of a less densely populated city affected the temperature during covid?

iv.Has the quarantine been effective in reducing the daily mean temperature or average temperature in general?

v.Did the daily average relative humidity increase or decrease over the span of Covid lock downs, also before and after the lock down what were the stats?

vi.Did the daily precipitation increase or decrease over the span of Covid lock downs, also before and after the lock down what were the stats?